-- Our Schema
CREATE TABLE IF NOT EXISTS Items (
  itemID INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  description TEXT,
  Q_in_stock INTEGER NOT NULL,
  price INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Cart (
  cartID INTEGER PRIMARY KEY AUTOINCREMENT,
  discID TEXT NOT NULL,
  itemID INTEGER NOT NULL,
  Q_selected INTEGER NOT NULL,
  subtotal INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Discount (
  discID TEXT PRIMARY KEY AUTOINCREMENT,
  description TEXT,
  percentage INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Customer (
  custID INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  cartID INTEGER NOT NULL,
  address TEXT NOT NULL,
  email TEXT NOT NULL,
  phone INTEGER NOT NULL,
  DOB DATE NOT NULL,
  gender TEXT NOT NULL,
  password TEXT NOT NULL,
);

CREATE TABLE IF NOT EXISTS Orders (
  orderID INTEGER PRIMARY KEY AUTOINCREMENT,
  custID INTEGER NOT NULL,
  status TEXT NOT NULL,
  total INTEGER NOT NULL,
  date DATE NOT NULL,
  recipient_name TEXT NOT NULL,
  shipping_address TEXT NOT NULL,
);

CREATE TABLE IF NOT EXISTS OrdersItems (
  orderID INTEGER NOT NULL
  itemID INTEGER NOT NULL,
  discID TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  totalSalePrice INTEGER NOT NULL,
  PRIMARY KEY(orderID, itemID)
);




-- Test Data
CREATE TABLE IF NOT EXISTS Sailors (
  sid INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  age INTEGER,
  experience INTEGER -- years of experience
);

CREATE TABLE IF NOT EXISTS Boats (
  bid INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  color TEXT
);

CREATE TABLE IF NOT EXISTS Voyages (
  sid INTEGER NOT NULL,
  bid INTEGER NOT NULL,
  date_of_voyage DATE NOT NULL,
  PRIMARY KEY(sid, bid, date_of_voyage)
);